In [1]:
import numpy as np 
import pandas as pandas
from matplotlib import pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

In [2]:
dataLabel = pandas.read_csv("D:/FreelancingWebsite/machineLearningModel/datasetModel/projectdataset.csv")
dataLabel

projectTitle
0                         Website Redesign
1                   Mobile App Development
2                 Content Writing for Blog
3   Graphic Design for Marketing Materials
4                  Data Entry and Analysis
5           E-commerce Website Development
6          Social Media Marketing Campaign
7        Video Editing for YouTube Channel
8                  Virtual Assistant Tasks
9             SEO Optimization for Website
10                 Logo Design for Startup
11                  Transcription Services
12                     Website Development
13                             Logo Design
14                         Content Writing
15                  Mobile App Development
16                              Data Entry
17                          Graphic Design
18                           Video Editing
19                      E-commerce Website
20                 Social Media Management
21                       Virtual Assistant
22                        SEO Optimization
23                        App UI/UX Design
24                        Blog Development
25                             Copywriting
26                    Translation Services
27                            Illustration
28                     Database Management
29                         IT Consultation
30                           Grant Writing
31                        Game Development
32                       Technical Support

In [3]:
dataSupplied = pandas.read_csv("D:/FreelancingWebsite/machineLearningModel/datasetModel//projectlabel.csv")
dataSupplied

expectedSkill
0        html,css,javascript,figma
1                          flutter
2              seo,content writing
3                        photoshop
4                            excel
5       html,css,javascript,nodejs
6                    communication
7                    communication
8         communication,data entry
9    seo,html,css,javascript,figma
10                       photoshop
11    attention to detail,writing 
12       html,css,javascript,figma
13                       photoshop
14             seo,content writing
15                    react-native
16                           excel
17                       photoshop
18    video editing,video creation
19      html,css,javascript,nodejs
20                 content writing
21                   communication
22  html,css,javascript,nodejs,seo
23                    react-native
24             html,css,javascript
25                    copy writing
26                 english,spanish
27                 content writing
28       database mangament system
29                   it consulting
30                 content writing
31                        c#,unity
32               technical support

In [4]:
from sklearn.model_selection import train_test_split
training_set,testing_set = train_test_split(dataSupplied,test_size=0.35,random_state=50)
training_set

expectedSkill
23                    react-native
10                       photoshop
31                        c#,unity
12       html,css,javascript,figma
3                        photoshop
14             seo,content writing
28       database mangament system
15                    react-native
7                    communication
2              seo,content writing
26                 english,spanish
30                 content writing
22  html,css,javascript,nodejs,seo
27                 content writing
5       html,css,javascript,nodejs
6                    communication
4                            excel
1                          flutter
13                       photoshop
11    attention to detail,writing 
32               technical support

In [5]:
from sklearn.model_selection import train_test_split
training_set_label,testing_set_label = train_test_split(dataLabel,test_size=0.35,random_state=50)
training_set_label

projectTitle
23                        App UI/UX Design
10                 Logo Design for Startup
31                        Game Development
12                     Website Development
3   Graphic Design for Marketing Materials
14                         Content Writing
28                     Database Management
15                  Mobile App Development
7        Video Editing for YouTube Channel
2                 Content Writing for Blog
26                    Translation Services
30                           Grant Writing
22                        SEO Optimization
27                            Illustration
5           E-commerce Website Development
6          Social Media Marketing Campaign
4                  Data Entry and Analysis
1                   Mobile App Development
13                             Logo Design
11                  Transcription Services
32                       Technical Support

In [6]:
vectorizer1 = CountVectorizer()
transformed_training_labels = vectorizer1.fit_transform(training_set_label)
transformed_training_labels

<1x1 sparse matrix of type '<class 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [7]:
vectorizer = CountVectorizer()
training_set_transformed = vectorizer.fit_transform(training_set)
training_set_transformed

<1x1 sparse matrix of type '<class 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [8]:
training_set_transformed.shape

(1, 1)

In [9]:
from sklearn.neighbors import KNeighborsClassifier 
regressor = KNeighborsClassifier(n_neighbors=1)
regressor.fit(training_set_transformed,transformed_training_labels)

c:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neighbors\_classification.py:233: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=1)

In [10]:
testing_set_transformed = vectorizer.fit_transform(testing_set)
testing_set_transformed

<1x1 sparse matrix of type '<class 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [11]:
testing_label_transformed = vectorizer1.fit_transform(testing_set_label)
testing_label_transformed

<1x1 sparse matrix of type '<class 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [12]:
testing_set_transformed.shape

(1, 1)

In [13]:
results = regressor.predict(testing_set_transformed)
results

array([<1x1 sparse matrix of type '<class 'numpy.int64'>'
       	with 1 stored elements in Compressed Sparse Row format>],
      dtype=object)

In [14]:
results_array_standard = results[0].toarray().flatten()
results_array_standard

array([1], dtype=int64)

In [15]:
labels_array_standard = testing_label_transformed.toarray().flatten()
labels_array_standard

array([1], dtype=int64)

In [16]:
accuracy = accuracy_score(results_array_standard,labels_array_standard)
accuracy

1.0

In [17]:
dataValidationLabel = pandas.read_csv("D:/FreelancingWebsite/machineLearningModel/datasetModel/dummyDatasetProject.csv")
dataValidationLabel

projectTitle
0               Implementing CI/CD Pipeline
1            Setting Up Kubernetes Clusters
2  Automating Infrastructure with Terraform
3           Configuring AWS Security Groups
4                Building Docker Containers
5         Deploying Serverless Applications
6              Managing IAM Policies in GCP
7                   Setting Up VPN in Azure
8              Implementing DDoS Protection
9           Auditing Cloud Security Posture

In [18]:
dataValidation = pandas.read_csv("D:/FreelancingWebsite/machineLearningModel/datasetModel//dummyDatasetLabel.csv")
dataValidation


expectedSkill
0  Continuous Integration/Continuous Deployment
1                     Kubernetes Administration
2         Infrastructure as Code with Terraform
3                    AWS Security Configuration
4                       Docker Containerization
5             Serverless Application Deployment
6          Google Cloud Platform IAM Management
7                               Azure VPN Setup
8                DDoS Protection Implementation
9             Cloud Security Posture Management

In [19]:
vectorizer3 = CountVectorizer()
transformed_validation_data = vectorizer3.fit_transform(dataValidation)
transformed_validation_data


<1x1 sparse matrix of type '<class 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [20]:
vectorizer4 = CountVectorizer() 
transformed_validation_label = vectorizer4.fit_transform(dataValidationLabel)
transformed_validation_label

<1x1 sparse matrix of type '<class 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [21]:
validation_results = regressor.predict(transformed_validation_data)
validation_results

array([<1x1 sparse matrix of type '<class 'numpy.int64'>'
       	with 1 stored elements in Compressed Sparse Row format>],
      dtype=object)

In [22]:
validation_data_array_standard = validation_results[0].toarray().flatten()
validation_data_array_standard

array([1], dtype=int64)

In [23]:
validation_label_transformed = transformed_validation_label.toarray().flatten()
validation_label_transformed

array([1], dtype=int64)

In [24]:
accuracy_validation = accuracy_score(validation_data_array_standard,validation_label_transformed)
accuracy_validation

1.0

In [25]:
from flask import Flask,request 

app = Flask(__name__)
@app.route('/v9/api/postSkillsFlask', methods = ['POST'])
def handleGetRequest() :
    data = request.get_json()
    skills = data['skillValue'] 
    return skills
    